### ISSUE TITLE
Azure Support

### ISSUE THREAD

**Issue by tevirgen** [koding/koding#8164]
**Goals**

Add support for azure and azurerm terraform providers to terraformer and kloud.

**Why**

Required support for Azure Cloud in stack templates.

**Acceptance Criteria**
- it is possible to build an Azure stack.

**Comment by gokmen** [comment]
@rjeczalik getting following error while building with azure provider;

```
o:azure_instance.azure-instance: Still creating... (10s elapsed)
e:Error applying plan:

1 error(s) occurred:

* azure_instance.azure-instance: You must supply a 'password' and/or a 'ssh_key_thumbprint' when using a Linux image

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
 (c7f9aafc71a79149)
```

here is my stack template;

```
provider:
  azure:
    publish_settings: '${var.azure_publish_settings}'
    subscription_id: '${var.azure_subscription_id}'

resource:
  azure_instance:
    # this is the name of your VM
    azure-instance:
      # select your instance size here: eg. Basic_A1
      size: Basic_A1
      # base image for your instance
      image: 'Ubuntu Server 14.04 LTS'
      # on custom_data section we will write bash and configure our VM
      custom_data: |-
        # let's create a file on your root folder:
        echo "hello world!" >> /helloworld.txt
```

you can try with #9319
