### ISSUE TITLE
klient/vagrant: failure provisioning multiple boxes at once

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#8696]
Stack template:

```
resource:
  vagrant_instance:
    localvm_1:
      cpus: 1
      memory: 1024
      box: ubuntu/trusty64
      user_data: |-
        sudo apt-get install sl -y
        touch /tmp/${var.koding_user_username}.txt
    localvm_2:
      cpus: 1
      memory: 1024
      box: ubuntu/trusty64
      user_data: |-
        sudo apt-get install sl -y
        touch /tmp/${var.koding_user_username}.txt
```

Result:

```
* vagrant_instance.localvm_2: vagrant provisioning has failed: 4 error(s) occurred:

* The machine 'urtv4bda0a8c_default_1470207023335_27433' is already locked for a session (or being unlocked)
* Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
* Context: "LockMachine(a->session, LockType_Write)" at line 493 of file VBoxManageModifyVM.cpp
* exit status 1
```

VirtualBox does not handle creating multiple boxes at once, instead we should set them up sequentially without provisioning and provision them concurrently afterwards.
