### ISSUE TITLE
vagrant/client: the "installing software" step is missing

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9040]
When building vagrant stack the "Installing software" step after "Checking VM connections" is missing, and it used to be there.

## Expected Behavior

Modal should tail on /var/log/cloud-init-output.log

## Current Behavior

It does tail.

## Possible Solution

It should tail.

## Steps to Reproduce (for bugs)

1. Build a vagrant stack.

## Your Environment

team.koding.com

**Comment by gokmen** [comment]
@alex-ionochkin can u check this issue and make it work with vagrant provider as well like we did for aws provider? Thanks!

**Comment by alex-ionochkin** [comment]
Actually `Installing software` step appears after `Checking VM Connections` but it's visible for a short period of time and then it quickly changes to success screen. The reason of it is that once VM is ready and `/var/log/cloud-init-output.log` is loaded logs file already contains `_KD_DONE_` which is a signal to show success screen on the modal. I tried different `sleep` values in `user_data` section of stack template to make a software installation longer but every time I got the same result - `Installing software` step quickly disappeared.
It looks like `user_data` instructions are done before modal `apply finished` event comes from the kloud. For example, if I run a simple vagrant stack without any delay:
```
resource:
  vagrant_instance:
    localvm:
      cpus: 2
      memory: 2048
      box: ubuntu/trusty64
      user_data: |-
        sudo apt-get install sl -y
        touch /tmp/${var.koding_user_username}.txt
```
it takes ~2 min. If I run the same template with 2 mins of `sleep`:
```
resource:
  vagrant_instance:
    localvm:
      cpus: 2
      memory: 2048
      box: ubuntu/trusty64
      user_data: |-
        sudo apt-get install sl -y
        touch /tmp/${var.koding_user_username}.txt
        sleep 120
```
it takes ~4min and most of time is taken by `Building stack resources` step.

@rjeczalik, could you please check on the kloud if machine already has `_KD_DONE_` in `/var/log/cloud-init-output.log` before kloud sends `apply finished` stack event to the client? If it's so, modal can't show `Installing Software` step since it's already done
