### ISSUE TITLE
terraformer: failure decoding numeric values in yaml/json template

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9085]
When a value is provided as a numeric literal, pasing the template (decoding on terraform side) fails with:

```
[18:14:51] Starting to process the template...
[18:14:51] Something went wrong with the template:
[18:14:51] At -: root.cloudflare_record.www.ttl: unknown type *ast.LiteralType (error code: 900)
[18:14:51] Parsing failed, please check your template and try again
```

Example template:

```
provider:
  aws:
    access_key: '${var.aws_access_key}'
    secret_key: '${var.aws_secret_key}'
  cloudflare:
    email: "bc"
    token: "asd"

resource:
  cloudflare_record:
    www:
      domain: "asd"
      name: "terraform"
      value: "192.168.0.11"
      type: "A"
      ttl: 3600
  aws_instance:
    example-instance:
      instance_type: t2.nano
      ami: ''
      tags:
        Name: '${var.koding_user_username}-${var.koding_group_slug}'
      user_data: |-
        echo "hello world!" >> /helloworld.txt
```

If `resource_cloudflare_record.www.ttl` is changed to strings literal instead, like:

```
  cloudflare_record:
    www:
      domain: "asd"
      name: "terraform"
      value: "192.168.0.11"
      type: "A"
      ttl: "3600"
```

The parsing completes successfully. It may be worth first updating terraform (https://github.com/koding/koding/issues/9084) before troubleshooting this issue.
