### ISSUE TITLE
klient/vagrant: add version to stack template

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9120]
Add version field to vagrant stack template:

```yaml
resource:
  vagrant_instance:
    localvm:
      cpus: 2
      memory: 2048
      box:
      - name: ubuntu/trusty64
      - version: 20160919.0.0
      user_data: |-
        sudo apt-get install sl -y
        touch /tmp/${var.koding_user_username}.txt
```

Make the `box` syntax backward compatible. If not possible (Terraform schema), then add separate `version` field instead.

On klient/vagrant side if version is empty or set to a `default` string - use the version, which already exists and is downloaded. This fixes problem, when install-kd.sh script tests whether ubuntu/trusty64 box exists, but does not checks versions and continues without updating box. Then, when vagrant stack is built, the build times out due to klient/vagrant updating the box. Fix also install-kd.sh script to update the default box.

Summary:

- fix install-kd.sh to update default box
- add `box/version` or `version` field support to kloud + terraformer + klient/vagrant and vagrantutil
- make klient/vagrant always use existing box to not download / update unnecessarily
