### ISSUE TITLE
klient, koding/server: use sysvinit for ubuntu:14.04

### ISSUE THREAD

**Issue by rjeczalik** [koding/koding#9764]
Upstart does not work inside Docker, which makes klient fail to start for ubuntu:14.04-based containers, and effectively break builds of marathon stacks if user decides to overwrite container command with cmd attribute, like:

```
resource:
  marathon_app:
    app:
      cmd: |-
         echo "hello world!" > ~/koding.txt

         while sleep 300; do true; done
        
      container:
        docker:
        - image: ubuntu:14.04
          network: BRIDGE

      instances: 1

      cpus: 1.0
      mem: 256
```

A workaround is to ensure `/opt/kite/klient/klient` is last line of cmd script, like:

 ```
resource:
  marathon_app:
    app:
      cmd: |-
         echo "hello world!" > ~/koding.txt
         
         /opt/kite/klient/klient
        
      container:
        docker:
        - image: ubuntu:14.04
          network: BRIDGE

      instances: 1

      cpus: 1.0
      mem: 256
```

Making koding/service to use sysvinit instead of upstart fixes that.
